-- WARNING: This will delete all existing data in the 'contacts' table!
-- Run this only if you want a completely fresh start.

-- 1. Drop the existing table and all its data
DROP TABLE IF EXISTS public.contacts;

-- 2. Re-create the table with ALL required columns
CREATE TABLE public.contacts (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text,          -- Combined name
    first_name text,    -- Separate first name
    last_name text,     -- Separate last name
    email text,
    phone text,
    course text,
    message text
);

-- 3. Set up Security (RLS)
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

-- 4. Allow anyone (public) to submit forms
CREATE POLICY "Enable insert for everyone" 
ON public.contacts 
FOR INSERT 
TO anon 
WITH CHECK (true);

-- 5. Allow only authenticated users (admins) to view data
CREATE POLICY "Enable read access for authenticated users only"
ON public.contacts
FOR SELECT
TO authenticated
USING (true);
