
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';
import { c4cContent } from '../lib/c4cContent';
import { cpiContent } from '../lib/cpiContent';

// Load environment variables from .env.local
dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error('Missing Supabase credentials!');
    process.exit(1);
}

// const supabase = createClient(supabaseUrl, supabaseKey); // Commented out as supabase client is no longer used for direct DB interaction

async function restoreCourses() {
    console.log('Generating SQL for SAP C4C Technical and SAP CPI...');

    const coursesToRestore = [
        {
            id: 'c4c-technical',
            title: 'SAP C4C Technical',
            category: 'Technical',
            hero_heading: 'End-to-End SAP C4C Technical Training with Real-Time Implementation',
            hero_subheading: '',
            description: c4cContent.description || 'Master SAP C4C Technical with our comprehensive training.',
            hero_image: '/images/ERPVITS - All Modules Infographics/ERPVITS - SAP C4C Tech Infographic.webp',
            duration: '40-50 Hours',
            price: 'Competitive',
            syllabus_url: '/syllabus/ERPVITS Syllabus - Course Contents Pdf/SAP Technical/sap-c4c-technical.pdf',
            meta_title: 'SAP C4C Technical Training',
            meta_description: 'Master SAP C4C Technical with our comprehensive training.',
            sections: c4cContent.sections,
            features: [], // Will be extracted if needed, or just left empty/default
            curriculum: [], // Should be in sections
            faqs: []
        },
        {
            id: 'cpi',
            title: 'SAP CPI',
            category: 'Technical',
            hero_heading: cpiContent.heroHeading,
            hero_subheading: cpiContent.heroSubheading,
            description: cpiContent.description,
            hero_image: '/images/ERPVITS - All Modules Infographics/ERPVITS - SAP CPI Infographic.webp',
            duration: '40-50 Hours',
            price: 'Competitive',
            syllabus_url: cpiContent.syllabusUrl,
            meta_title: cpiContent.metaTitle,
            meta_description: cpiContent.metaDescription,
            sections: cpiContent.sections,
            features: [],
            curriculum: [],
            faqs: []
        }
    ];

    let sqlContent = `-- Restore SAP C4C Technical and SAP CPI
-- Generated by script

`;

    for (const course of coursesToRestore) {
        const { id, title, category, hero_heading, hero_subheading, description, hero_image, duration, price, meta_title, meta_description, sections, features, curriculum, faqs } = course;

        const escapeSql = (str: string | undefined) => str ? `'${str.replace(/'/g, "''")}'` : 'NULL';
        const jsonSql = (obj: any) => obj ? `'${JSON.stringify(obj).replace(/'/g, "''")}'::jsonb` : `'[]'::jsonb`;

        const sql = `
INSERT INTO public.courses (
  id, title, category, hero_heading, hero_subheading, description, hero_image, duration, price, meta_title, meta_description, sections, features, curriculum, faqs
) VALUES (
  ${escapeSql(id)},
  ${escapeSql(title)},
  ${escapeSql(category)},
  ${escapeSql(hero_heading)},
  ${escapeSql(hero_subheading)},
  ${escapeSql(description)},
  ${escapeSql(hero_image)},
  ${escapeSql(duration)},
  ${escapeSql(price)},
  ${escapeSql(meta_title)},
  ${escapeSql(meta_description)},
  ${jsonSql(sections)},
  ${jsonSql(features)},
  ${jsonSql(curriculum)},
  ${jsonSql(faqs)}
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  hero_heading = EXCLUDED.hero_heading,
  hero_subheading = EXCLUDED.hero_subheading,
  description = EXCLUDED.description,
  hero_image = EXCLUDED.hero_image,
  duration = EXCLUDED.duration,
  price = EXCLUDED.price,
  meta_title = EXCLUDED.meta_title,
  meta_description = EXCLUDED.meta_description,
  sections = EXCLUDED.sections,
  features = EXCLUDED.features,
  curriculum = EXCLUDED.curriculum,
  faqs = EXCLUDED.faqs;
`;
        sqlContent += sql;
    }

    fs.writeFileSync('restore_c4c_cpi.sql', sqlContent);
    console.log('Generated restore_c4c_cpi.sql');
}

restoreCourses();
